export enum Role {
  ADMIN = "ADMIN",
  SUBADMIN = "SUBADMIN",
  USER = "USER",
  GOOGLEUSER = "GOOGLEUSER",
}

export enum AccessType {
  ACTIVE = "ACTIVE",
  BLOCKED = "BLOCKED",
}

export enum ProductStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum TokenType {
  SIGNUP = "SIGNUP",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
}

export enum EmailType {
  SIGNUP = "SIGNUP",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  EXPENSE = "EXPENSE",
}

export const expenseCategories = [
  {
    id: "food",
    name: "Food",
    icon: "🍕",
    keywords: [
      "food",
      "restaurant",
      "eat",
      "meal",
      "lunch",
      "dinner",
      "breakfast",
      "cafe",
      "pizza",
      "burger",
      "pav bhaji",
      "dosa",
      "vada pav",
      "snack",
      "drink",
      "biryani",
      "thali",
      "curry",
      "paratha",
      "idli",
      "sambar",
      "samosa",
      "chole",
      "naan",
      "tandoori",
      "paneer",
      "south indian",
      "north indian",
      "buffet",
      "dhaba",
    ],
  },
  {
    id: "streetfood",
    name: "Street Food",
    icon: "🍲",
    keywords: [
      "street food",
      "chaat",
      "golgappa",
      "panipuri",
      "bhelpuri",
      "sevpuri",
      "pani puri",
      "tikki",
      "aloo tikki",
      "vada pav",
      "dabeli",
      "frankies",
      "roll",
      "kachori",
      "chhole kulche",
      "bhajji",
      "pakoda",
      "momos",
      "chat",
      "thela",
      "roadside",
      "jalebi",
      "fafda",
      "dhokla",
    ],
  },
  {
    id: "shopping",
    name: "Shopping",
    icon: "🛍",
    keywords: [
      "shopping",
      "clothes",
      "fashion",
      "mall",
      "store",
      "buy",
      "purchase",
      "shirt",
      "shoes",
      "bag",
      "kurta",
      "saree",
      "salwar",
      "lehenga",
      "dhoti",
      "ethnic",
      "western",
      "kurtis",
      "jeans",
      "footwear",
      "chappal",
      "jewellery",
      "accessories",
      "myntra",
      "ajio",
      "flipkart",
      "amazon",
      "meesho",
      "showroom",
    ],
  },
  {
    id: "grocery",
    name: "Grocery",
    icon: "🛒",
    keywords: [
      "grocery",
      "supermarket",
      "vegetables",
      "fruits",
      "milk",
      "bread",
      "rice",
      "dal",
      "oil",
      "market",
      "atta",
      "wheat",
      "pulses",
      "masala",
      "spices",
      "ghee",
      "paneer",
      "curd",
      "dahi",
      "sabzi",
      "kirana",
      "general store",
      "big basket",
      "grofers",
      "zepto",
      "blinkit",
      "dmart",
      "reliance fresh",
      "big bazaar",
      "sabziwala",
    ],
  },
  {
    id: "transportation",
    name: "Transportation",
    icon: "🚗",
    keywords: [
      "uber",
      "ola",
      "taxi",
      "bus",
      "train",
      "metro",
      "fuel",
      "petrol",
      "diesel",
      "auto",
      "rickshaw",
      "rapido",
      "scooter",
      "bike",
      "scooty",
      "activa",
      "local train",
      "irctc",
      "railway",
      "flight",
      "air ticket",
      "indigo",
      "spicejet",
      "airasia",
      "vistara",
      "toll",
      "fastag",
      "parking",
      "challan",
      "cng",
      "e-rickshaw",
      "toto",
    ],
  },
  {
    id: "entertainment",
    name: "Entertainment",
    icon: "🎬",
    keywords: [
      "movie",
      "cinema",
      "game",
      "party",
      "club",
      "bar",
      "music",
      "concert",
      "show",
      "netflix",
      "pvr",
      "inox",
      "bookmyshow",
      "amazon prime",
      "hotstar",
      "disney+",
      "zee5",
      "sonyliv",
      "bowling",
      "gaming",
      "playstation",
      "xbox",
      "arcade",
      "water park",
      "theme park",
      "adventure",
      "pub",
      "lounge",
      "disc",
      "karaoke",
      "standup",
      "comedy",
    ],
  },
  {
    id: "bills",
    name: "Bills",
    icon: "📄",
    keywords: [
      "electricity",
      "water",
      "gas",
      "internet",
      "mobile",
      "phone",
      "wifi",
      "bill",
      "recharge",
      "subscription",
      "broadband",
      "dth",
      "tatasky",
      "airtel",
      "jio",
      "vi",
      "bsnl",
      "cable",
      "postpaid",
      "prepaid",
      "landline",
      "cylinder",
      "lpg",
      "maintenance",
      "society",
      "apartment",
      "housing",
      "municipal",
      "property tax",
    ],
  },
  {
    id: "healthcare",
    name: "Healthcare",
    icon: "🏥",
    keywords: [
      "doctor",
      "medicine",
      "hospital",
      "clinic",
      "pharmacy",
      "medical",
      "health",
      "checkup",
      "treatment",
      "ayurvedic",
      "homeopathic",
      "allopathic",
      "dental",
      "dentist",
      "eye",
      "optician",
      "spectacles",
      "glasses",
      "contacts",
      "lens",
      "covid",
      "test",
      "vaccination",
      "insurance",
      "physiotherapy",
      "surgery",
      "consultation",
      "apollo",
      "fortis",
      "max",
      "pharmeasy",
      "1mg",
      "netmeds",
      "pathology",
    ],
  },
  {
    id: "emi",
    name: "EMI",
    icon: "💳",
    keywords: [
      "emi",
      "loan",
      "credit",
      "installment",
      "mortgage",
      "bank",
      "payment",
      "finance",
      "hdfc",
      "icici",
      "sbi",
      "axis",
      "bajaj",
      "home loan",
      "car loan",
      "personal loan",
      "education loan",
      "credit card",
      "rbi",
      "interest",
      "repayment",
      "mudra",
      "nbfc",
    ],
  },
  {
    id: "education",
    name: "Education",
    icon: "📚",
    keywords: [
      "education",
      "school",
      "college",
      "university",
      "tuition",
      "coaching",
      "course",
      "class",
      "fees",
      "books",
      "stationery",
      "uniform",
      "exam",
      "admission",
      "semester",
      "hostel",
      "iit",
      "neet",
      "jee",
      "upsc",
      "byju's",
      "unacademy",
      "vedantu",
      "library",
      "workshop",
      "certification",
      "scholarship",
      "private",
      "convent",
    ],
  },
  {
    id: "religious",
    name: "Religious/Charity",
    icon: "🙏",
    keywords: [
      "temple",
      "donation",
      "charity",
      "puja",
      "pooja",
      "mandir",
      "church",
      "mosque",
      "gurudwara",
      "religious",
      "spiritual",
      "ritual",
      "priest",
      "pandit",
      "bhajan",
      "kirtan",
      "aarti",
      "offering",
      "prasad",
      "langar",
      "zakat",
      "tithe",
      "ngo",
      "fundraiser",
      "volunteer",
      "hundi",
      "havan",
    ],
  },
  {
    id: "festivals",
    name: "Festivals/Gifts",
    icon: "🎁",
    keywords: [
      "festival",
      "gift",
      "diwali",
      "holi",
      "raksha bandhan",
      "rakhi",
      "eid",
      "christmas",
      "navratri",
      "durga puja",
      "ganesh chaturthi",
      "birthday",
      "anniversary",
      "wedding",
      "shaadi",
      "present",
      "celebration",
      "function",
      "party",
      "reception",
      "engagement",
      "return gift",
      "baby shower",
      "godh bharai",
      "tilak",
      "mehendi",
    ],
  },
  {
    id: "rent",
    name: "Home/Rent",
    icon: "🏠",
    keywords: [
      "rent",
      "lease",
      "apartment",
      "flat",
      "house",
      "accommodation",
      "pg",
      "hostel",
      "furniture",
      "appliance",
      "repair",
      "maintenance",
      "renovation",
      "decor",
      "paint",
      "housing",
      "property",
      "broker",
      "security deposit",
      "advance",
      "tenant",
      "landlord",
      "rental",
      "agreement",
      "society",
      "builder",
      "interior",
      "plumbing",
      "electric",
      "carpenter",
    ],
  },
  {
    id: "personalcare",
    name: "Personal Care",
    icon: "💇",
    keywords: [
      "salon",
      "spa",
      "haircut",
      "massage",
      "facial",
      "makeup",
      "cosmetics",
      "beauty",
      "barber",
      "grooming",
      "skin care",
      "hair color",
      "manicure",
      "pedicure",
      "waxing",
      "threading",
      "parlour",
      "nykaa",
      "lakme",
      "loreal",
      "nivea",
      "garnier",
      "dermatologist",
      "body lotion",
      "face wash",
      "shampoo",
      "conditioner",
      "perfume",
      "deodorant",
    ],
  },
  {
    id: "electronics",
    name: "Electronics",
    icon: "📱",
    keywords: [
      "electronics",
      "gadget",
      "phone",
      "mobile",
      "laptop",
      "computer",
      "tablet",
      "tv",
      "television",
      "fridge",
      "refrigerator",
      "washing machine",
      "ac",
      "air conditioner",
      "microwave",
      "oven",
      "camera",
      "headphone",
      "earphone",
      "speakers",
      "smartwatch",
      "apple",
      "samsung",
      "oneplus",
      "mi",
      "xiaomi",
      "oppo",
      "vivo",
      "realme",
      "lenovo",
      "hp",
      "dell",
    ],
  },
  {
    id: "travel",
    name: "Travel/Vacation",
    icon: "✈",
    keywords: [
      "travel",
      "vacation",
      "trip",
      "tour",
      "holiday",
      "flight",
      "hotel",
      "resort",
      "booking",
      "homestay",
      "airbnb",
      "oyo",
      "makemytrip",
      "yatra",
      "goibibo",
      "irctc",
      "sightseeing",
      "tourism",
      "beach",
      "mountain",
      "hill station",
      "goa",
      "shimla",
      "manali",
      "kerala",
      "pondicherry",
      "agra",
      "jaipur",
      "passport",
      "visa",
    ],
  },
  {
    id: "investment",
    name: "Investment",
    icon: "📈",
    keywords: [
      "investment",
      "stock",
      "share",
      "mutual fund",
      "fd",
      "fixed deposit",
      "rd",
      "recurring deposit",
      "ppf",
      "nps",
      "gold",
      "silver",
      "crypto",
      "bitcoin",
      "zerodha",
      "groww",
      "upstox",
      "angel",
      "demat",
      "trading",
      "nifty",
      "sensex",
      "dividend",
      "interest",
      "return",
      "pension",
      "provident fund",
      "pf",
      "sip",
      "insurance premium",
      "lic",
    ],
  },
  {
    id: "familysupport",
    name: "Family Support",
    icon: "👨‍👩‍👧‍👦",
    keywords: [
      "family",
      "parents",
      "support",
      "allowance",
      "pocket money",
      "relative",
      "sibling",
      "mother",
      "father",
      "grandparents",
      "aunt",
      "uncle",
      "cousin",
      "remittance",
      "transfer",
      "upi",
      "paytm",
      "gpay",
      "phonepe",
      "domestic help",
      "maid",
      "driver",
      "cook",
      "caretaker",
      "elder care",
      "child care",
      "babysitter",
    ],
  },
  {
    id: "stationery",
    name: "Stationery/Office",
    icon: "✏",
    keywords: [
      "stationery",
      "office supplies",
      "pen",
      "pencil",
      "notebook",
      "diary",
      "paper",
      "printer",
      "ink",
      "cartridge",
      "stapler",
      "file",
      "folder",
      "tape",
      "marker",
      "highlighter",
      "xerox",
      "photocopy",
      "print",
      "lamination",
      "binding",
      "rubber stamp",
      "visiting card",
      "business card",
      "classmate",
      "camlin",
      "reynolds",
    ],
  },
  {
    id: "fitness",
    name: "Fitness/Sports",
    icon: "🏋",
    keywords: [
      "fitness",
      "gym",
      "workout",
      "exercise",
      "sports",
      "yoga",
      "zumba",
      "dance",
      "swimming",
      "cricket",
      "football",
      "badminton",
      "tennis",
      "coach",
      "trainer",
      "membership",
      "equipment",
      "protein",
      "supplement",
      "cult",
      "trueweight",
      "decathlon",
      "marathon",
      "cycling",
      "jogging",
      "running",
      "sportswear",
      "athleisure",
    ],
  },
  { id: "other", name: "Other", icon: "💸", keywords: [] },
];